#!/bin/bash

awk -F: '{print $1 ":" $3 ":" $6}' /etc/passwd

# Awk  scans  each input file for lines that match any of a set
# of patterns specified literally in prog or in one
# or more files specified as -f progfile.
# -f - separator
